/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cdb45126-9036-4e7e-81d2-df4e7566da54",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rTUwDeeHu",
    "aws_user_pools_web_client_id": "61fqrbv8dm6omh5lt79gklk90k",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xo6b4pks5ncmrkyyadroyj4r4i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
